---
title: "Data Manipulation"
output: github_document
---

```{r set up}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```


## 'select'

Choose some columns and not others

```{r}
select(litters_df, group, litter_number)
select(litters_df,gd0_weight:gd_of_birth)
select(litters_df,-litter_number)
```

Renaming columns

```{r}
select(litters_df, GROUP = group, LITTer_Number = litter_number)
```

```{r}
rename(litters_df, GROUP = group, LITTer_Number = litter_number)
```


Select helpers

```{r}
select(litters_df,starts_with("gd"))
select(litters_df,litter_number, everything())
relocate(litters_df,litter_number)
```




## 'filter'

```{r}
filter(litters_df, gd0_weight < 22)
filter(litters_df,gd_of_birth == 20)
filter(litters_df,gd_of_birth != 20)
```

```{r}
filter(litters_df,gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df,group == "Mod8")
filter(litters_df,group %in% c("Con7", "Mod8"))
```





## "mutate"

Create new column
Modify existing column

```{r}
mutate(litters_df,
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```




## 'arrange'

Put things in order

```{r}
arrange(litters_df,pups_born_alive)
arrange(litters_df,pups_born_alive, gd0_weight)
```
























